version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ivens
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: trading_journal
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
